---
shell_packages:
  - zsh

  - starship
  - fzf
  - zoxide
  
  - eza
  - bat
  - ripgrep
  - fd
  - tealdeer

  - jq
  - p7zip
  - unzip
  - fastfetch
  - tree
  - wget
  - github-cli
  - python-pip

shell_symlinks:
  - eza
  - zsh
  - npm
  - starship.toml
