[icons]
"firefox" = "ï‰© "
"librewolf" = "ï‰© "
"kitty" = "ï„  "
"Spotify" = "ï†¼ "
"WebCord" = "ï‡¿ "
"obsidian" = "ï…œ "
"Gimp" = "îŸ§ "
"WhatsApp" = "ğŸ—©"
"dolphin" = "ó±¢´ "
"Tor Browser" = "ï± "
"PolyMC" = "ó°³ "
"Zathura" = "ó°ˆ¦"
"libreoffice-writer" = "ï¼ "
"libreoffice-impress" = "ïº "
"libreoffice-calc" = "ï· "
"Anki" = "ï€­ "
"Plug" = "ó°‹… "

[aliases.class]
"Gimp*" = "Gimp"
".[Mm]inecraft*" = "PolyMC"

[aliases.instance]
"web\\.whatsapp\\.com" = "Whatsapp"

[general]
display_property = "class"
empty_label = "ï„‘ "

[options]
no_names = true
