---
- hosts: local
  connection: local
  # obtain system info like the ansible_facts
  gather_facts: yes
  become: no
  vars:
    dotfiles_dir: "{{ ansible_facts.user_dir }}/Repos/dotfiles" 
    config_dir: "{{ ansible_facts.user_dir }}/.config"

  roles:
    - desktop
    - shell
