---
desktop_packages:
  - i3-wm
  - polybar
  - rofi
  - picom
  - dunst
  - autorandr
  - feh
  - imagemagick
  - xclip
  - maim
  - brightnessctl
  - ufw
  - lightdm
  - lightdm-gtk-greeter
  - zsh

  # GUI apps
  - zathura
  - zathura-pdf-mupdf
  - thunar
  - firefox
  - kitty

  # bluetooth
  - bluez
  - bluez-utils
  - blueman

  - ttf-firacode-nerd 

desktop_aur_packages:
  - pulseaudio-control
  - synology-drive
  - librewolf-bin
  - i3wsr-git
  - bibata-cursor-theme

user_directories:
  - Desktop
  - Downloads
  - Documents
  - Videos
  - Music
  - Repos
  - Drive
  - Pictures
  - Pictures/wallpapers
  - Pictures/screenshots
  - .local/share/applications
  - .local/share/virtualenvs

desktop_symlinks:
  - i3
  - polybar
  - rofi
  - dunst
  - picom
  - autorandr
  - i3wsr
  - zathura
  - kitty
